### ISSUE TITLE
ResNetASD is missing

### ISSUE THREAD

**Issue by gorayhan08** [IrohXu/ViTASD#2]
In 6th line of `train_affectnet.py, `
`from models import ViTASD, ResNetASD`
where `ResNetASD` is missing.

**Comment by IrohXu** [comment]
> In 6th line of `train_affectnet.py, `
> `from models import ViTASD, ResNetASD`
> where `ResNetASD` is missing.

You can delete ResNetASD in this line. In this repo, we only publish the ViT baseline for pretraining. ResNet50/ResNet152 was only used in lab's private repo for ablation study. Thanks for pointing out this problem. The full version code will release together with our new dataset soon.

**Comment by gorayhan08** [comment]
If you are using any specific version of python packages in this code, it would be very helpful to mention those in the requirements section. TIA.

**Comment by IrohXu** [comment]
> If you are using any specific version of python packages in this code, it would be very helpful to mention those in the requirements section. TIA.

Thanks for your suggestions. I will update a requirements.txt later.

**Comment by m0012023** [comment]
> If you are using any specific version of python packages in this code, it would be very helpful to mention those in the requirements section. TIA.

Did you run the code successfully?
