### ISSUE TITLE
Is this repository complete?

### ISSUE THREAD

**Issue by HuiyingCH** [IrohXu/ViTASD#3]
I tried several times to run the complete code as per your instructions, but unable to run it. Some functions are missing. Can you provide me with the complete code?
It would be very helpful.

**Comment by IrohXu** [comment]
Hi, you can comment out: `from models import ViTASD, ResNetASD` and only use `from models import ViTASD`.

See https://github.com/IrohXu/ViTASD/issues/2

**Comment by HuiyingCH** [comment]
In train.py 
   self.valid_acc = Accuracy()
TypeError: __new__() missing 1 required positional argument: 'task'
What is its solution?

**Comment by HuiyingCH** [comment]
In train.py line no: 41  
pretrain_path: str = ""
What is the pretrained_path here?

**Comment by IrohXu** [comment]
First, use AffectNet dataset to pretraining the model if you need the pretrained weight. Otherwise don't use the pretrained weight.
[train_affectnet.py](https://github.com/IrohXu/ViTASD/blob/main/train_affectnet.py)

**Comment by HuiyingCH** [comment]
Thank you very much. I need another help.
Tell me something about this checkpoint in eval.py line no (31-35)
```
model = ViTASDLM.load_from_checkpoint(
    checkpoint_path="",
    hparams_file="",
    map_location=None,
)
```

It is not actually being understood by me.

**Comment by IrohXu** [comment]
After you train the model with `train.py`, you will obtain the checkpoint weight in a log folder. Please fill the path of checkpoint weight into `checkpoint_path=""`. And use `eval.py` to calculate the AUROC and Accuracy.

**Comment by HuiyingCH** [comment]
Thank you so much.
